steps:
  - id: 'build-app-image'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/muzieh-firecast/muzieh-firecast-repo/node-build:tag1', '.' ]
  - id: 'push-app-image'
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ['build-app-image']
    args: ['push', 'us-central1-docker.pkg.dev/muzieh-firecast/muzieh-firecast-repo/node-build:tag1']
  - name: 'ubuntu'
    args: ['bash', '-c', 'echo "test message"']
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['push-app-image']
    script: |
      gcloud run deploy firecast-api --image us-central1-docker.pkg.dev/muzieh-firecast/muzieh-firecast-repo/node-build:tag1 --region us-central1 --platform managed --allow-unauthenticated
