steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/muzieh-firecast/muzieh-firecast-repo/node-build:tag1', '.' ]
images:
  - 'us-central1-docker.pkg.dev/muzieh-firecast/muzieh-firecast-repo/node-build:tag1'
