steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/muzieh-firecast/firecast/node-build', '.' ]
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/muzieh-firecast-repo/node-build:latest'
