substitutions:
  _REVISION: ${_VERSION}-${SHORT_SHA}
  _IMAGE_NAME: 'us-central1-docker.pkg.dev/muzieh-firecast/muzieh-firecast-repo/node-build'
  
steps:
  - id: 'build-app-image'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_IMAGE_NAME}:${COMMIT_SHA}', '.' ]
  - id: 'push-app-image'
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ['build-app-image']
    args: ['push', '${_IMAGE_NAME}:${COMMIT_SHA}']
  # - name: 'ubuntu'
  #   args: ['bash', '-c', 'echo "${_REVISION}"']
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['push-app-image']
    entrypoint: 'bash'
    args: 
      - '-c'
      - >
        gcloud run deploy firecast-api 
        '--image=${_IMAGE_NAME}:${COMMIT_SHA}'
        '--region=us-central1'
        '--platform=managed'
        '--allow-unauthenticated'
        '--tag=${_REVISION}'
images:
  - '$_IMAGE_NAME:$COMMIT_SHA'
options:
  machineType: E2_MEDIUM
