substitutions:
  _REVISION: ${_VERSION}-${SHORT_SHA}
  _IMAGE_NAME: 'us-central1-docker.pkg.dev/muzieh-firecast/muzieh-firecast-repo/node-build'
  
steps:
  - id: 'build-app-image'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_IMAGE_NAME}:tag1', '.' ]
  - id: 'push-app-image'
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ['build-app-image']
    args: ['push', '${_IMAGE_NAME}:tag1']
  - name: 'ubuntu'
    args: ['bash', '-c', 'echo "${_REVISION}:tag1"']
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['push-app-image']
    entrypoint: 'bash'
    args: 
      - '-c'
      - >
        gcloud run deploy firecast-api 
        '--image=${_IMAGE_NAME}:tag1'
        '--region=us-central1'
        '--platform=managed'
        '--allow-unauthenticated'
